; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = espidf
build_flags = 
    -D ESP_ENV=1
    -D SLEEP_MODE_PERIOD_MS=2000000
    -D ACTIVE_MODE_PERIOD_MS=1000000
    
[env:prod]
extends = env:esp32-s3-devkitm-1
build_flags = -D ESP_ENV=1
