#ifndef PHOTORES_ANALOG_CHANNEL
#define PHOTORES_ANALOG_CHANNEL ADC_CHANNEL_1
#endif


#ifndef LED_PIN_DEFAULT
#define LED_PIN_DEFAULT GPIO_NUM_1
#endif

#ifndef LED_SWITCH_VOLTAGE
#define LED_SWITCH_VOLTAGE 1100
#endif

